spring:
  application:
    name: "gatewayserver"

  config:
    import:
      - "optional:configserver:http://localhost:8071"

  cloud:
    gateway:
      actuator:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   # REQUIRED for lowercase service names
      httpclient: # httpclient timeout configuration, global for all microservices routes
        connect-timeout: 1000
        response-timeout: 2s

    discovery:
      prefer-ip-address: true
      client:
        service-url:
          defaultZone: http://eureka-ms:8761/eureka/
        register-with-eureka: true
        fetch-registry: true


eureka:
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-ms:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
    info:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "eazybank gateway server application"
    version: "1.0.0"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000