services:

  eureka:
    image: prateekarya100/eureka:ms
    container_name: eureka-ms
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://eureka-ms:8761/actuator/health | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accountsdb:
    image: mysql:8.0
    container_name: accountsdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app1db
      MYSQL_USER: app1user
      MYSQL_PASSWORD: app1pass
    ports:
      - "3301:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  cardsdb:
    image: mysql:8.0
    container_name: cardsdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app2db
      MYSQL_USER: app2user
      MYSQL_PASSWORD: app2pass
    ports:
      - "3302:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  loansdb:
    image: mysql:8.0
    container_name: loansdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app3db
      MYSQL_USER: app3user
      MYSQL_PASSWORD: app3pass
    ports:
      - "3303:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: prateekarya100/configserver:ms
    container_name: configserver-ms
    ports:
      - "8071:8071"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/prateekarya100/configserver.git"
      SPRING_RABBITMQ_HOST: rabbit
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_PROFILES_ACTIVE: git
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: main
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://configserver-ms:8071/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: prateekarya100/accounts:ms
    container_name: accounts-ms
    ports:
      - "8081:8081"

    #     ports:
    #       - "8081"

    #    dynamic host ports
    #    ports:
    #      - "2001-2004:8081"
    #    deploy:
    #      replicas: 3   # scale to 3 containers
    #      restart_policy:
    #        condition: on-failure

    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_DATASOURCE_URL: jdbc:mysql://accountsdb:3306/app1db
      SPRING_DATASOURCE_USERNAME: app1user
      SPRING_DATASOURCE_PASSWORD: app1pass
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-ms:8761/eureka/
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
      eureka:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: prateekarya100/cards:ms
    container_name: cards-ms
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_DATASOURCE_URL: jdbc:mysql://cardsdb:3306/app2db
      SPRING_DATASOURCE_USERNAME: app2user
      SPRING_DATASOURCE_PASSWORD: app2pass
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-ms:8761/eureka/
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
      eureka:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: prateekarya100/loans:ms
    container_name: loans-ms
    ports:
      - "8083:8083"
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_DATASOURCE_URL: jdbc:mysql://loansdb:3306/app3db
      SPRING_DATASOURCE_USERNAME: app3user
      SPRING_DATASOURCE_PASSWORD: app3pass
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-ms:8761/eureka/
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
      eureka:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: bridge
